### ISSUE TITLE
null pointer dereference and segfault in eval_shell (src/shc.c:708)

### ISSUE THREAD

**Issue by geeknik** [neurobin/shc#34]
Feeding a file that contains only `#!0` to shc triggers a null pointer dereference and crash.

`echo '#!0' > test.sh && ./shc -f test.sh -o /dev/null`

```
==22425==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000402ccf sp 0x7ffe41c46e70 bp 0x000000000000 T0)
    #0 0x402cce in eval_shell /root/shc/src/shc.c:708
    #1 0x40b083 in do_all /root/shc/src/shc.c:1001
    #2 0x401806 in main /root/shc/src/shc.c:1013
    #3 0x7fea3d22ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #4 0x4018ec (/root/shc/src/shc+0x4018ec)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/shc/src/shc.c:708 eval_shell
==22425==ABORTING
```

**Comment by neurobin** [comment]
The shebang line is mandatory..

```bash
printf '#!/bin/bash\necho #!0' > test.sh && shc -f test.sh
```
